name: laser_slides
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/icons/appIcon.jpg" 
  android: true
  ios: true

flutter:
  uses-material-design: true
  


  fonts:
    - family: sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf



  assets:
    - assets/icons/
    - assets/images/
